name: Release Build

on:
  push:
    branches: main

jobs:
  release:
    name: Release Build
    runs-on: ubuntu-latest
    outputs:
      version: $semver
    steps:
      - uses: actions/checkout@v2
      - uses: CupOfTea696/gh-action-auto-release@v1.0.2
        with:
          title: $semver
          tag: $semver
          changelog-entry: Overview
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge_source:
    name: Merge Source Code Branches
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Clone Source Code Repository
        run: |
          git clone https://${{ secrets.GH_PAT }}@github.com/GeroiGorodskoyZastroiki/ISUTC.git

      - name: Merge dev into main
        run: |
          cd ISUTC
          git config user.email "${{ secrets.EMAIL }}"
          git config user.name "${{ secrets.GH_NAME }}"
          git checkout dev
          git checkout main
          git merge dev -m "${{ needs.release.outputs.version }}"
          git push