name: Release Build

on:
  push:
    branches: main

jobs:
  release:
    name: Release Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CupOfTea696/gh-action-auto-release@v1.0.2
        with:
          title: $semver
          tag: $semver
          changelog-entry: Overview
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  merge_source:
    name: Merge Source Code Branches
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Clone Source Code Repository
        run: |
          git clone https://${{ secrets.GH_PAT }}@github.com/${{ vars.GH_USER }}/${{ vars.GH_SOURCE_CODE_REPO }}.git

      - name: Merge dev into main
        run: |
          cd ISUTC
          git config user.email "${{ secrets.EMAIL }}"
          git config user.name "${{ vars.GH_USER }}"
          git checkout ${{ vars.GH_SOURCE_CODE_BRANCH_FROM }}
          git checkout ${{ vars.GH_SOURCE_CODE_BRANCH_INTO }}
          echo ${{ needs.release.outputs.version }}
          git merge ${{ vars.GH_SOURCE_CODE_BRANCH_FROM }}
          git push
